#MySql credentials

# MySql server IP
MySql_Hostname: 94.130.53.190
# Name of the MySql database (Default: QNicks)
MySql_Database: test
# MySql username
MySql_User: quapi_test
# MySql password
MySql_Password: PFf@egL_54!yzfLI
# MySql server port (Default: 3306)
MySql_Port: 3306
# Use SSL?
MySql_UseSSL: false


# ~ Config Version: 0.0.1 ~ #