#MySql credentials

# MySql server IP
MySql_Hostname:
# Name of the MySql database (Default: QNicks)
MySql_Database: QNicks
# MySql username
MySql_User:
# MySql password
MySql_Password:
# MySql server port (Default: 3306)
MySql_Port: 3306
# Use SSL?
MySql_UseSSL: false


# ~ Config Version: 0.0.1 ~ #